#!/usr/bin/env python3
"""LLM170_* env 플래그 카탈로그 생성 (plans/75 P4.1).

소스에서 LLM170_[A-Z0-9_]+ 를 추출해 출현 파일·횟수와 분류를 표로 만든다.
분류는 scripts/env-classify.json 이 없으면 이름 규칙으로 추정한다.

사용:
  python3 scripts/env-catalog.py            # 표준출력
  python3 scripts/env-catalog.py --write    # docs/configuration.md 갱신
"""
import argparse
import collections
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAT = re.compile(r"LLM170_[A-Z0-9_]+")
# 이름 규칙 기반 추정 분류 (운영/검증/진단/실험·플랜 옵인)
DIAG_PAT = re.compile(r"(KTRACE|TRACE|DBG|DEBUG|TIME|PROF|DUMP|PTRACE|WALL|SRV_TIME|NP_TIME|LAUNCH|PPROF)")
VERIFY_PAT = re.compile(r"(EXACT|CHECK|GATE|DIFF|REF|SELF|PROBE)")
ABLATION_PAT = re.compile(r"^(LLM170_)?(NO_|F32|KV8|ATOM|SPLIT|TILE|BATCH|FUSE)")


def classify(name: str, curated: dict) -> str:
    if name in curated:
        return curated[name]
    if DIAG_PAT.search(name):
        return "diag"
    if VERIFY_PAT.search(name):
        return "verify"
    if ABLATION_PAT.search(name.replace("LLM170_", "")):
        return "ablation"
    return "operational?"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    curated = {}
    cf = ROOT / "scripts" / "env-classify.json"
    if cf.exists():
        curated = json.loads(cf.read_text())

    hits = collections.defaultdict(lambda: [0, collections.Counter()])
    for p in sorted((ROOT / "crates").rglob("*.rs")):
        for m in PAT.finditer(p.read_text(errors="replace")):
            name = m.group(0)
            hits[name][0] += 1
            hits[name][1][str(p.relative_to(ROOT))] += 1

    rows = []
    for name, (n, files) in sorted(hits.items()):
        top = ", ".join(f"{f}({c})" for f, c in files.most_common(2))
        rows.append((classify(name, curated), name, n, len(files), top))

    out = ["# Configuration — environment variables",
           "",
           f"{len(rows)} unique `LLM170_*` variables across the workspace "
           f"({sum(r[2] for r in rows)} references). Generated by "
           "`scripts/env-catalog.py` (plans/75 P4).",
           "",
           "| class | variable | refs | files | where (top 2) |",
           "|---|---|---|---|---|"]
    for c, name, n, nf, top in sorted(rows):
        out.append(f"| {c} | `{name}` | {n} | {nf} | {top} |")
    text = "\n".join(out) + "\n"
    print(text if not a.write else f"wrote docs/configuration.md ({len(rows)} vars)")
    if a.write:
        (ROOT / "docs" / "configuration.md").write_text(text)


if __name__ == "__main__":
    main()
