[package]
name = "llm170-backend-gpu"
version.workspace = true
edition.workspace = true

[dependencies]
llm170-profiler = { path = "../profiler" }
llm170-core = { path = "../core" }
llm170-gguf = { path = "../gguf" }
cubecl-runtime = "0.10.0"
cubecl = { version = "0.10.0", features = ["wgpu"] }
hanzo-cubecl-hip = "0.10.0"
bytemuck = "1"
half = "2"
