[package]
name = "llm170-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "llm170"
path = "src/main.rs"

[dependencies]
half = "2"
memmap2 = "0.9"
llm170-gguf = { path = "../gguf" }
llm170-profiler = { path = "../profiler" }
llm170-core = { path = "../core" }
llm170-backend-gpu = { path = "../backend-gpu" }
log = "0.4"
